import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Mail, Phone, MapPin, Instagram, Twitter, Facebook, Youtube, ArrowRight } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
const ShopFooter = () => {
    const [email, setEmail] = useState('');
    return (_jsxs("footer", { className: "bg-foreground text-primary-foreground mt-16", children: [_jsx("div", { className: "border-b border-white/10", children: _jsxs("div", { className: "max-w-[1280px] mx-auto px-5 py-10 flex flex-col md:flex-row items-center justify-between gap-6", children: [_jsxs("div", { children: [_jsx("h3", { className: "font-display text-xl font-bold", children: "Stay in the loop" }), _jsx("p", { className: "text-sm text-white/60 mt-1", children: "Subscribe for exclusive deals, new arrivals & more." })] }), _jsxs("form", { onSubmit: (e) => { e.preventDefault(); setEmail(''); }, className: "flex w-full max-w-md", children: [_jsx("input", { type: "email", value: email, onChange: (e) => setEmail(e.target.value), placeholder: "Enter your email", className: "flex-1 px-4 py-3 rounded-l-xl bg-white/10 border border-white/15 text-sm text-white placeholder:text-white/40 outline-none focus:border-white/30 transition-colors" }), _jsxs("button", { type: "submit", className: "px-5 py-3 rounded-r-xl bg-accent text-white font-semibold text-sm flex items-center gap-1.5 hover:brightness-110 transition-all", style: { background: 'hsl(var(--accent))' }, children: ["Subscribe ", _jsx(ArrowRight, { size: 14 })] })] })] }) }), _jsxs("div", { className: "max-w-[1280px] mx-auto px-5 py-12 grid grid-cols-2 md:grid-cols-4 gap-10", children: [_jsxs("div", { className: "col-span-2 md:col-span-1", children: [_jsxs("div", { className: "font-display font-bold text-xl mb-4", children: ["Shop", _jsx("span", { style: { color: 'hsl(var(--accent))' }, children: "Smart" })] }), _jsx("p", { className: "text-sm text-white/50 leading-relaxed mb-5", children: "Your one-stop destination for premium products at unbeatable prices. Quality guaranteed." }), _jsx("div", { className: "flex gap-3", children: [
                                    { icon: Instagram, label: 'Instagram' },
                                    { icon: Twitter, label: 'Twitter' },
                                    { icon: Facebook, label: 'Facebook' },
                                    { icon: Youtube, label: 'YouTube' },
                                ].map(({ icon: Icon, label }) => (_jsx("a", { href: "#", "aria-label": label, className: "w-9 h-9 rounded-full bg-white/10 flex items-center justify-center hover:bg-white/20 transition-colors", children: _jsx(Icon, { size: 16 }) }, label))) })] }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-sm uppercase tracking-wider mb-4 text-white/80", children: "Shop" }), _jsx("ul", { className: "space-y-2.5", children: ['New Arrivals', 'Best Sellers', 'Sale', 'Collections', 'Gift Cards'].map((l) => (_jsx("li", { children: _jsx(Link, { to: "/", className: "text-sm text-white/50 hover:text-white transition-colors", children: l }) }, l))) })] }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-sm uppercase tracking-wider mb-4 text-white/80", children: "Company" }), _jsx("ul", { className: "space-y-2.5", children: ['About Us', 'Careers', 'Blog', 'Press', 'Sustainability'].map((l) => (_jsx("li", { children: _jsx(Link, { to: "/", className: "text-sm text-white/50 hover:text-white transition-colors", children: l }) }, l))) })] }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-sm uppercase tracking-wider mb-4 text-white/80", children: "Contact" }), _jsxs("ul", { className: "space-y-3", children: [_jsxs("li", { className: "flex items-start gap-2.5 text-sm text-white/50", children: [_jsx(MapPin, { size: 15, className: "mt-0.5 shrink-0 text-white/40" }), _jsx("span", { children: "123 Commerce St, Mumbai, India 400001" })] }), _jsxs("li", { className: "flex items-center gap-2.5 text-sm text-white/50", children: [_jsx(Phone, { size: 15, className: "shrink-0 text-white/40" }), _jsx("span", { children: "+91 98765 43210" })] }), _jsxs("li", { className: "flex items-center gap-2.5 text-sm text-white/50", children: [_jsx(Mail, { size: 15, className: "shrink-0 text-white/40" }), _jsx("span", { children: "support@shopsmart.in" })] })] })] })] }), _jsx("div", { className: "border-t border-white/10", children: _jsxs("div", { className: "max-w-[1280px] mx-auto px-5 py-5 flex flex-col sm:flex-row items-center justify-between gap-3", children: [_jsxs("p", { className: "text-xs text-white/40", children: ["\u00A9 ", new Date().getFullYear(), " ShopSmart. All rights reserved."] }), _jsx("div", { className: "flex gap-5", children: ['Privacy Policy', 'Terms of Service', 'Refund Policy'].map((l) => (_jsx(Link, { to: "/", className: "text-xs text-white/40 hover:text-white/70 transition-colors", children: l }, l))) }), _jsxs("div", { className: "flex gap-2 items-center", children: [_jsx("span", { className: "text-xs text-white/40", children: "We accept:" }), ['💳', '🏦', '📱', '🔒'].map((e) => _jsx("span", { className: "text-base", children: e }, e))] })] }) })] }));
};
export default ShopFooter;
